export const MSG_ADD_TO_CART_SUCCESS = 'Add to Cart Successfully !'
export const MSG_UPDATE_CART_SUCCESS = 'Cart updated Successfully !'
export const MSG_DELETE_PRODUCT_FROM_CART_SUCCESS = 'Product Removed Successfully !'
export const MSG_CART_EMPTY = 'Cart Is Empty !'
export const MSG_PRODUCT_LIST_EMPTY = 'Product List Is Empty !'
export const MSG_WELCOME = 'Welcome to My Website !'