export const MSG_ADD_TO_CART_SUCCESS = 'Add to Cart successfully !'
export const MSG_UPDATE_CART_SUCCESS = 'Cart updated successfully !'
export const MSG_DELETE_PRODUCT_FROM_CART_SUCCESS = 'Product removed successfully'
export const MSG_CART_EMPTY = 'Cart is empty !'
export const MSG_WELCOME = 'Welcome to my Website !'